global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    # metrics_path defaults to '/metrics'
#    # scheme defaults to 'http'.
#    static_configs:
#      - targets: [ '127.0.0.1:9090' ]

  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.49:8080']